name: action for testing

on:
  push:
    branches: [main]
    
  workflow_dispatch:

jobs:
  build:
    name: Dashboard 
    runs-on: ubuntu-latest
    steps: 
      - name: curl call to api
        run: |
          curl -i -u "dvalleit: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" https://api.github.com/users/octocat
